name: Test
on:
  push:
    branches:
      - dev
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: no

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Test
        run: |
          echo "sleep"
          sleep 120

